In [66]:
import numpy as np
import pandas as pd
import pickle
from sklearn.utils import shuffle
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter

In [4]:
#from google.colab import drive
#drive.mount('/content/drive')

In [67]:
df = pd.read_csv('/content/drive/My Drive/cut.csv')
df.head()

id  ...                                               tags
0  5ef0d321d83b3587cb500efc  ...                      ["Quique Setien","Barcelona"]
1  5ef0d324d83b3587cb500efd  ...  ["Jose Mourinho","Harry Kane","Manchester unit...
2  5efff14f86936ae10d2be3c8  ...  ["Alvaro Morata","Mallorca","Diego Simeone","R...
3  5efff10a86936ae10d2be3aa  ...  ["Sourav Ganguly","Wasim Jaffer","India","Zahe...
4  5ef0d2e5d83b3587cb500edf  ...  ["Mumbai Indians","Jasprit Bumrah","Mahela Jay...

[5 rows x 8 columns]

In [ ]:
len(df.content.unique()),  len(df.content)

(18, 18)

In [ ]:
df.content[0]

'["The Video Assistant Referee (VAR) system is not being used correctly in La Liga, Barcelona manager Quique Setien said on Monday following Real Madrid’s controversial win at Real Sociedad.","Madrid beat Sociedad 2-1 to climb above Barcelona at the top of La Liga but the home side were aggrieved because they had a goal ruled out by VAR for offside and Karim Benzema’s winner stood after he appeared to control the ball with his arm.","“There are things that we cannot control and that do not depend on us. Everybody saw what happened in Anoeta and everyone will draw their own conclusions,” Setien told reporters ahead of Tuesday’s match against Athletic Bilbao.","“It’s understandable that we think why there are some actions that are reviewed, the referee himself reviews them and they don’t do the same in other plays. They do it on some matches and in some others (they don’t). So you could really think that (VAR) is not being used correctly.”","Setien said controversies were part of footbal

In [ ]:
# time range for which these articles are published
#min(df.date_published).split("T")[0], max(df.date_published).split("T")[0]

In [ ]:
# the number of articles in each section
Counter(df.topic)

Counter({'["cricket"]': 4, '["education"]': 11, '["football"]': 3})

In [ ]:
df.isnull().sum()

id             0
topic          0
heading        0
summary        0
date           0
sub-heading    0
content        0
tags           2
dtype: int64

In [68]:
df.dropna(subset=['content'], inplace = True)
df.dropna(subset = ['topic'], inplace = True)

In [ ]:
#df.shape

(148, 10)

In [69]:
import pandas as pd
import numpy as np
import re

import gensim
from gensim import corpora,models
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(2018)

import nltk
#nltk.download('wordnet')
#nltk.download('stopwords')

In [70]:
# data preprocessing
stemmer = SnowballStemmer(language='english',ignore_stopwords=True)
def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))
def preprocess(text):
    result = []
    for token in gensim.utils.simple_preprocess(text):
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
    return result

In [71]:
# preview after preprocessing
doc_sample = df['content'][0]
print('original document: ')
words = []
for word in doc_sample.split(' '):
    words.append(word)
print(words)
print('\n\n tokenized and lemmatized document: ')
print(preprocess(doc_sample))

original document: 
['["The', 'Video', 'Assistant', 'Referee', '(VAR)', 'system', 'is', 'not', 'being', 'used', 'correctly', 'in', 'La', 'Liga,', 'Barcelona', 'manager', 'Quique', 'Setien', 'said', 'on', 'Monday', 'following', 'Real', 'Madrid’s', 'controversial', 'win', 'at', 'Real', 'Sociedad.","Madrid', 'beat', 'Sociedad', '2-1', 'to', 'climb', 'above', 'Barcelona', 'at', 'the', 'top', 'of', 'La', 'Liga', 'but', 'the', 'home', 'side', 'were', 'aggrieved', 'because', 'they', 'had', 'a', 'goal', 'ruled', 'out', 'by', 'VAR', 'for', 'offside', 'and', 'Karim', 'Benzema’s', 'winner', 'stood', 'after', 'he', 'appeared', 'to', 'control', 'the', 'ball', 'with', 'his', 'arm.","“There', 'are', 'things', 'that', 'we', 'cannot', 'control', 'and', 'that', 'do', 'not', 'depend', 'on', 'us.', 'Everybody', 'saw', 'what', 'happened', 'in', 'Anoeta', 'and', 'everyone', 'will', 'draw', 'their', 'own', 'conclusions,”', 'Setien', 'told', 'reporters', 'ahead', 'of', 'Tuesday’s', 'match', 'against', 'Athlet

In [72]:
# Preprocess the headline text, saving the results as ‘processed_docs’
df['processed_heading'] = df['heading'].map(preprocess)
df['processed_content'] = df['content'].map(preprocess)
df['processed_topic'] = df['topic'].map(preprocess)
df['processed_heading'] = df['processed_heading'].apply(lambda x: ' '.join(x))
df['processed_content'] = df['processed_content'].apply(lambda x: ' '.join(x))
df['processed_topic'] = df['processed_topic'].apply(lambda x: ' '.join(x))
df.head() 

id  ... processed_topic
0  5ef0d321d83b3587cb500efc  ...         footbal
1  5ef0d324d83b3587cb500efd  ...         footbal
2  5efff14f86936ae10d2be3c8  ...         footbal
3  5efff10a86936ae10d2be3aa  ...         cricket
4  5ef0d2e5d83b3587cb500edf  ...         cricket

[5 rows x 11 columns]

In [73]:
#Split the data into a "train" and "test". As well as select a metric in which to measure the similarity between articles. Think of the "train" set as the corpus.
# Think of the "test" set as the NYT articles that users are currently reading.

# move articles to an array
articles = df.processed_content.values

# move article section names to an array
sections = df.processed_topic.values

# move article web_urls to an array
headings = df.processed_heading.values

# shuffle these three arrays 
articles, sections, headings = shuffle(articles, sections, headings, random_state=4)

In [74]:
# split the shuffled articles into two arrays
n = 3

# one will have all but the last 10 articles -- think of this as your training set/corpus 
X_train = articles[:-n]
X_train_headings = headings[:-n]
X_train_sections = sections[:-n]

# the other will have those last 10 articles -- think of this as your test set/corpus 
X_test = articles[-n:]
X_test_headings = headings[-n:]
X_test_sections = sections[-n:]

In [31]:
# instantiate your vectorizor 
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

In [45]:
# predicting document similarity
tfidf_matrix = tfidf_vectorizer.fit_transform(df.processed_heading[0:2])

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

#Calculate the similarity distance
similarity_distance = 1 - cosine_similarity(tfidf_matrix)

In [47]:
similarity_distance

array([[ 0.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00, -2.22044605e-16]])

In [32]:
# fit the vectorizer 
tfidf_vectorizer.fit(X_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
# transform both article splits 
X_train_tfidf = tfidf_vectorizer.transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [ ]:
#Builidng a Content Based Recommender
def get_top_n_rec_articles(X_train_tfidf, X_train, test_article, X_train_sections, X_train_headings, n = 5):
    '''This function calculates similarity scores bewteen a document and a corpus
    
       INPUT: vectorized document corpus, 2D array
              text document corpus, 1D array
              user article, 1D array
              article section names, 1D array
              article URLs, 1D array
              number of articles to recommend, int
              
       OUTPUT: top n recommendations, 1D array
               top n corresponding section names, 1D array
               top n corresponding URLs, 1D array
               similarity scores bewteen user article and entire corpus, 1D array
              '''
    # calculate similarity between the corpus (i.e. the "test" data) and the user's article
    similarity_scores = X_train_tfidf.dot(test_article.toarray().T)

    # get sorted similairty score indicies 
    sorted_indicies = np.argsort(similarity_scores, axis = 0)[::-1]

    # get sorted similarity socres
    sorted_sim_scores = similarity_scores[sorted_indicies]

    # get top n most similar documents
    top_n_recs = X_train[sorted_indicies[:n]]

    # get top n corresponding document section names
    rec_sections = X_train_sections[sorted_indicies[:n]]

    # get top n corresponding urls
    rec_headings = X_train_headings[sorted_indicies[:n]]
    
    # return recommendations and corresponding article meta-data
    return top_n_recs, rec_sections, rec_headings, sorted_sim_scores

In [ ]:
# pick an article from the "test" set
# treat this as the article that the user is currently reading
k = 0
test_article = X_test_tfidf[k]

In [ ]:
# return the top n most similar articles as recommendations 
top_n_recs, rec_sections, rec_headings, sorted_sim_scores = \
get_top_n_rec_articles(X_train_tfidf, X_train,  test_article,X_train_sections, X_train_headings, n = 5 )

In [ ]:
#validate the results
#Compare the user's article and corresponding section name with the recommended articles and corresponding section names

# similarity scores
sorted_sim_scores[:5]

array([[[0.2246952 ]],

       [[0.22285593]],

       [[0.12201387]],

       [[0.09892844]],

       [[0.09773023]]])

In [ ]:
# user's article
X_test[k]

'jose mourinho launch impass defenc harri kane form play style tottenham hotspur televis pundit paul merson suggest england striker struggl portugues manag merson pundit sport say year kane consid switch club mourinho continu adopt conserv style premier leagu like draw manchest unit week kane score seven goal game mourinho struggl impact unit match return hamstr surgeri januari mourinho say merson wrong judg base game record goal harri charg easi striker play mourinho tell report virtual news confer monday minut long respons mourinho go mention like didier drogba cristiano ronaldo karim benzema diego milito zlatan ibrahimov reel goal score stat tenur club dear paul lot respect mourinho add think harri kane problem score goal team especi fresh routin play good news injuri mourinho confirm forward luca moura avail recov injuri dele alli content serv match suspens time arriv attack player avail game mourinho say match final peopl play bench rotat player attack option match good'

In [ ]:
# user's article's section name
X_test_sections[k]

'footbal'

In [ ]:
# corresponding section names for top n recs 
rec_sections

array([['footbal'],
       ['footbal'],
       ['cricket'],
       ['cricket'],
       ['cricket']], dtype=object)

In [ ]:
# top n article recs
top_n_recs

array([['alvaro morata score twice lead atletico madrid mallorca extend strong finish spanish leagu friday diego simeon team long titl race disput leader real madrid second place barcelona trail point atlético hottest team liga tick shift focus champion leagu final play portug month march leagu halt atlético struggl secur champion leagu berth season cours finish atlético remain undef seven match spanish leagu resum follow month stoppag covid pandem complic situat stoppag play play play great attitud morata say simeon domin releg threaten mallorca kickoff morata earn penalti pull aleksandar sedlar area goalkeep manuel reina block strike video review help refere order redo spot kick sedlar enter area earli morata step second rifl ball corner minut miss get tri footbal morata say penalti chelsea real madrid striker scoreboard half injuri time jorg koke resurrección steal ball play marco llorent clear reach line morata post home goal morata season leagu play mallorca muster comeback renan 

In [ ]:
# corresonding URLs for top n recs 
rec_headings

array([['morata doubl lead atletico mallorca liga'],
       ['correct barcelona coach setien'],
       ['jasprit bumrah differ beast go middl mumbai indian head coach mahela jayawarden'],
       ['head coach phil simmon rejoin team mandatori quarantin covid test'],
       ['sourav ganguli sehwag open bring yuvraj zaheer harbhajan india open wasim jaffer name best captain play']],
      dtype=object)

In [60]:
unique_topics = set(X_test_sections)
unique_topics

{'cricket', 'educ', 'footbal'}

In [64]:
# text classification
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

In [16]:
categories = [str(x) for x in unique_topics]
categories

['cricket', 'educ', 'footbal']

In [96]:
n_components = 3
#labels = data_train.target
#true_k = np.unique(labels).shape[0]
data_train = X_train
topic_train = X_train_sections

data_test = X_test
topic_test = X_test_sections

#true_k = len(categories)
# convert to TF-IDF format
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(data_train)

# Reduce dimensions
svd = TruncatedSVD(n_components)
normalizer = Normalizer(copy=False)
lsa = make_pipeline(svd, normalizer)

X_train_vec = lsa.fit_transform(X_train_vec)

In [85]:
data_test

array(['jose mourinho launch impass defenc harri kane form play style tottenham hotspur televis pundit paul merson suggest england striker struggl portugues manag merson pundit sport say year kane consid switch club mourinho continu adopt conserv style premier leagu like draw manchest unit week kane score seven goal game mourinho struggl impact unit match return hamstr surgeri januari mourinho say merson wrong judg base game record goal harri charg easi striker play mourinho tell report virtual news confer monday minut long respons mourinho go mention like didier drogba cristiano ronaldo karim benzema diego milito zlatan ibrahimov reel goal score stat tenur club dear paul lot respect mourinho add think harri kane problem score goal team especi fresh routin play good news injuri mourinho confirm forward luca moura avail recov injuri dele alli content serv match suspens time arriv attack player avail game mourinho say match final peopl play bench rotat player attack option match good',
 

In [97]:
# order of labels in `target_names` can be different from `categories`
#target_names = data_train.target_names
# split a training set and a test set
y_train_vec, y_test_vec = topic_train, topic_test

print("Extracting features from the test data using the same vectorizer")
X_test_vec = vectorizer.transform(data_test)
X_test_vec = lsa.fit_transform(X_test_vec)

Extracting features from the test data using the same vectorizer


In [92]:
from sklearn.naive_bayes import GaussianNB

In [98]:
gnb = GaussianNB()
y_pred_NB = gnb.fit(X_train_vec, y_train_vec).predict(X_test_vec)

In [99]:
y_pred_NB

array(['educ', 'educ', 'educ'], dtype='<U7')

In [100]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred_NB))
print(metrics.confusion_matrix(y_test, y_pred_NB))

              precision    recall  f1-score   support

     cricket       0.00      0.00      0.00         1
        educ       0.33      1.00      0.50         1
     footbal       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3

[[0 1 0]
 [0 1 0]
 [0 1 0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [81]:
from sklearn.svm import SVC

In [82]:
svm = SVC()
y_pred_SVM = svm.fit(X_train_vec, y_train_vec).predict(X_test_vec)

In [83]:
y_pred_SVM

array(['educ', 'educ', 'cricket'], dtype=object)

In [101]:

print(metrics.classification_report(y_test, y_pred_SVM))
print(metrics.confusion_matrix(y_test, y_pred_SVM))

              precision    recall  f1-score   support

     cricket       0.00      0.00      0.00         1
        educ       0.50      1.00      0.67         1
     footbal       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.17      0.33      0.22         3
weighted avg       0.17      0.33      0.22         3

[[0 1 0]
 [0 1 0]
 [1 0 0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
